name: Run Selenium Tests Daily

on:
  schedule:
    - cron: '0 0 * * *'   # Runs once every day at 00:00 UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-tests:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code # This step checks out the repository code
        uses: actions/checkout@v3 # Use the latest version of checkout action

      - name: Set up Java # Set up Java environment for Maven
        uses: actions/setup-java@v3 # Set up Java environment
        with:
          distribution: 'temurin' # Use Temurin distribution for Java 
          java-version: '11' # Specify Java version 8

      - name: Cache Maven packages # Cache Maven dependencies to speed up builds
        uses: actions/cache@v3 # Cache action for Maven dependencies
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} # Cache key based on OS and pom.xml hash
          restore-keys: ${{ runner.os }}-maven

      - name: Run tests with Maven # Execute Maven to run tests
        run: mvn clean test # Clean and run tests using Maven
